env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
overrides:
  - rules:
      no-console: off
    files:
      - ./bin/*.js
