env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions:
    - error
    - ignorePackages
overrides:
  - rules:
      no-console: off
    files:
      - ./bin/*.js
